<a href="https://colab.research.google.com/github/inhyeeeeee/machine-learning/blob/main/%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC_220616.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **언어 모델(LM, Language Model)**
* 문장에 확률을 할당하는 모델
* 통계 vs AI
* 이전 단어들이 주어졌을 때 다음 단어를 예측
* 주어진 양쪽의 단어들로부터 가운데 비어있는 단어를 예측
* Language Modeling

---

1. Languasge Model, LM
- 기계 번역 (Machine Translation)
P(나는 버스를 탔다) > P(나는 버스를 태운다) * P:확률

- 오타교정 (Spell Correction)
선생님이 교실로 부리나케 P(달려갔다) > P(잘려갔다)

- 음성인식(Speech Recognition)
P(나는 메롱을 먹는다) < P(나는 메론을 먹는다)

- 문장의 확률 (W:문장, w:단어)
P(W) = p(w1,w2,w3,...wn)
다음 단어 (n번째) 등장 확률
P(W) = P(wn|w1, ..., wn-1)
P(w5|w1,w2,w3,w4)
P(W) = P(w1,w2,w3,...,wn) = ㅠni=1P(wi|w1,...,wi-1) 
비행기를 타려고 공항에 갔는데 지각을 하는 바람에 비행기를 [?]


---

2. Statical Language Model, SLM
- 조건부 확률
- 'An adorable little boy is spreading smiles'
- P('An adorable little boy is spreading smiles')
- P(w1,w2,w3,...,wn) = ㅠni=1P(wi|w1,...,wi-1)
- P(is|'An adorable little boy')=30%
- 카운트를 기반으로 하기 때문에 Sparsity problem 이 있음


---
3. N-gram
- 모든 단어를 고려하는 것이 아니라 일부 단어만 고려하는 모델
- P(is|An adorable little boy)=P(is|boy)
- P(is|An adorable little boy)=P(is|little boy)
- n은 단어를 몇개 볼지 : unigrams, bigrams, trigrams, 4-grams...
- 근데 P(insults|boy is spreading)=0.500, P(smiles|boy is spreading)=0.200 이라 insults 로 나와버림. 적절한 선 찾기
- 보통 N <= 5 (문장이 길어질수록 갖고있는 코퍼스에서 그 문장이 존재하지 않을 가능성이 높음)
- Domain(marketing text? medical text?)
- Generalization
- Neural Network


---
4. 한국어 모델
- 어순이 중요하지 않아 다음 단어 예측 어려움
- 그녀가, 그녀를, 그녀의, 그녀와, 그녀로, 그녀처럼 등
- 굴절어(영어) : I, My, Me, Mine
- 교착어(한국어) : 나는, 내가, 나의, 나를(어간+어미 분리하여 훈련시켜야함)
- 고립어 : 한자
- 띄어쓰기 후 학습 필요


---
5. 언어 모델 성능 평가
- Perplexity, PPL, P(W)
- 특정 시점에서 평균적으로 몇 개의 선택지를 가지고 고민하는지를 의미 = branching factor
- 점수가 낮을수록 성능이 좋음.
- 

---

6. Word Representation
- 어떤 안어가 특정 문서 내에서 얼마나 중요한 것인지
- 문서의 핵심어 추출
- 검색 엔진에서 검색 결과의 순위 결정
문서들 간의 유사도를 구하는 등의 용도 등
- local representation : puppy 라는 단어를 카운트 (one-hot vector, n-gram, count based(DTM (dacument term matrix) - TF-IDF))
- distributed representation : puppy 라는 단어와 함께 많이 쓰인 단어를 매핑 (뉘앙스)


---
7. Bag of Words, BoW
- 단어의 등장 순서를 고려하지 않고 빈도수를 계산하여 수치화


In [86]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [87]:
from konlpy.tag import Okt

okt = Okt()

def build_bag_of_words(document):
  # 온점 제거 및 형태소 분석(토큰화)
  document = document.replace('.', '')
  tokenized_document = okt.morphs(document)

  word_to_index = {}
  bow = []

  for word in tokenized_document:  # 토큰화된 문서에서 word 추출
    if word not in word_to_index.keys(): # word_to_index 의 키에 word 가 없다면
      word_to_index[word] = len(word_to_index) # word 키 값 생성 및 word_to_index 길이별로 집넣겠다.(count 하겠다)
      # bow에 전부 기본값 1을 넣는다.
      bow.insert(len(word_to_index) - 1, 1)
    else: # word 가 있으면
      # 재등장하는 단어의 인덱스
      index = word_to_index.get(word)
      # 재등장한 단어는 해당하는 인덱스의 위치에 1을 더한다.
      bow[index] = bow[index] + 1

  return word_to_index, bow

doc1 = "정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다."
vocab, bow = build_bag_of_words(doc1)
print('vocabulary :', vocab)
print('bag of words vector :', bow)

doc2 = '소비자는 주로 소비하는 상품을 기준으로 물가상승률을 느낀다.'
vocab, bow = build_bag_of_words(doc2)
print('vocabulary :', vocab)
print('bag of words vector :', bow)

doc3 = doc1 + ' ' + doc2 # 빈도수를 전체로 잡음
vocab, bow = build_bag_of_words(doc3)
print('vocabulary :', vocab)
print('bag of words vector :', bow)

vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
bag of words vector : [1, 2, 1, 1, 2, 1, 1, 1, 1, 1]
vocabulary : {'소비자': 0, '는': 1, '주로': 2, '소비': 3, '하는': 4, '상품': 5, '을': 6, '기준': 7, '으로': 8, '물가상승률': 9, '느낀다': 10}
bag of words vector : [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1]
vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9, '는': 10, '주로': 11, '소비': 12, '상품': 13, '을': 14, '기준': 15, '으로': 16, '느낀다': 17}
bag of words vector : [1, 2, 1, 2, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1]


In [88]:
# CountVectorizer 클래스 : 단어의 빈도를 count 하여 vector 로 생성
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['you know I want your love. because I love you.']
vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
# print('bag of words vector :', vector.fit_transform(corpus)) 
print('bag of words vector :', vector.fit_transform(corpus).toarray()) 

# 각 단어의 인덱스가 어떻게 부여되었는지를 출력
print('vocabulary :',vector.vocabulary_)

bag of words vector : [[1 1 2 1 2 1]]
vocabulary : {'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [89]:
corpus = ['정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.']
vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
# print('bag of words vector :', vector.fit_transform(corpus)) 
print('bag of words vector :', vector.fit_transform(corpus).toarray()) 

# 각 단어의 인덱스가 어떻게 부여되었는지를 출력
print('vocabulary :',vector.vocabulary_)

bag of words vector : [[1 1 1 1 1 1 1]]
vocabulary : {'정부가': 6, '발표하는': 4, '물가상승률과': 2, '소비자가': 5, '느끼는': 0, '물가상승률은': 3, '다르다': 1}


In [90]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

# 사용자가 직접 정의한 불용어
text = ["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print('bag of words vector :',vect.fit_transform(text).toarray())
print('vocabulary :',vect.vocabulary_)

# CountVectorizer 에서 제공하는 자체 불용어
vect = CountVectorizer(stop_words="english")
print('bag of words vector :',vect.fit_transform(text).toarray())
print('vocabulary :',vect.vocabulary_)

# NLTK 에서 지원하는 불용어
import nltk
nltk.download('stopwords')
nltk_stop_words = stopwords.words("english")
vect = CountVectorizer(stop_words=nltk_stop_words)
print('bag of words vector :',vect.fit_transform(text).toarray()) 
print('vocabulary :',vect.vocabulary_)

bag of words vector : [[1 1 1 1 1]]
vocabulary : {'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}
bag of words vector : [[1 1 1]]
vocabulary : {'family': 0, 'important': 1, 'thing': 2}
bag of words vector : [[1 1 1 1]]
vocabulary : {'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Document Term Matrix
- 다수의 document 에 등장하는 각 단어들의 빈도를 행렬로 표현한 것


> TF-IDF
1. Term Frequency-Inverse Document Frequency
2. DTM 내의 각 단어들마다 중요한 정도를 가중치 (DTM -> TF-IDF 가중치 부여)
3. 문서의 유사도, 검색 결과의 중요도, 특정 단어의 중요도
4. TF-IDF:TF*IDF (document:d, term:t, total number of document:n)
5. tf(d,t): 특정 문서 d에서의 특정 단어 t의 등장 횟수(DTM)
6. df(t):특정 단어 t가 등장한 문서의 수
7. idf(d,t):df(t) 에 반비례하는 수, idf(d,t)=log(n/(1+df(t))
( 특정 문서에서 특정 단어가 자주 등장한다면 중요하지 않은 단어로 땅땅)




In [91]:
import pandas as pd # 데이터프레임 사용을 위해
from math import log # IDF 계산을 위해

docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 
vocab = list(set(w for doc in docs for w in doc.split())) # 중복이 빠진 집합을 리스트화
vocab.sort() # vocab : DTM 의 열(term 리스트) 생성

N = len(docs) # 총 문서의 수

def tf(t, d): # 특정 문서 d 에서 특정 단어 t 의 등장횟수
  return d.count(t)

def idf(t): # 특정 단어 t가 등장한 문서 d 수
  df = 0
  for doc in docs:
    df += t in doc
  return log(N/(df+1))

def tfidf(t, d): # t의 중요도 가중치
  return tf(t,d)* idf(t)

result = []
# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [92]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])
idf_


IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [93]:
result = []
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [94]:
### 사이킷런 이용한 DTM , TF-IDF
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print(vector.fit_transform(corpus).toarray())

# 각 단어와 맵핑된 인덱스 출력
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


Vector Similarity
- 문장이나 문서의 유사도 구하기
- 기계가 계산하는 문서의 유사도의 성능은 각 문서의 단어들을 어떤 방법으로 수치화하여 표현했는지, 문서 간의 단어들의 차이를 어떤 방법(유클리드 거리, 코사인 유사도 등)으로 계산했는지에 달림

> 1. 코사인 유사도
> - 두 벡터 간의 코사인 각도를 이용하여 구할 수 있는 두 벡터의 유사도
> - 두 벡터의 방향이 동일하다면 1, 90도의 각을 이루면 0, 180도로 반대의 방향이라면 -1 값
> - -1이상 1이하의 값
> - 1에 가까울 수록 유사도가 높다고 판단. 즉, 두 벡터가 가리키는 방향이 얼마나 유사한가를 의미




In [95]:
# 넘파이를 사용하여 코사인 유사도 계산하는 함수 구현
# 각 문서 벡터 간의 코사인 유사도 계산
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

doc1 = np.array([0,1,1,1])
doc2 = np.array([1,0,1,1])
doc3 = np.array([2,0,2,2])

print('문서 1과 문서2의 유사도 :',cos_sim(doc1, doc2))
print('문서 1과 문서3의 유사도 :',cos_sim(doc1, doc3))
print('문서 2와 문서3의 유사도 :',cos_sim(doc2, doc3)) # 벡터로 좌표상에 찍으면 같은 방향이라 유사도는 1

문서 1과 문서2의 유사도 : 0.6666666666666667
문서 1과 문서3의 유사도 : 0.6666666666666667
문서 2와 문서3의 유사도 : 1.0000000000000002


In [96]:
# 영화 추천시스템
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv('movies_metadata.csv', low_memory=False)
data.head(2)

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   

                               homepage    id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story   862  tt0114709                en   
1                                   NaN  8844  tt0113497                en   

  original_title                                           overview  ...  \
0      Toy Story  Led by Woody, Andy's toys live happily in his ...  ...   
1        Jumanji  When siblings Judy and Peter discover an encha...  ...   

  release_date      revenue runtime  \
0   1995-10-30  373554033.0    81.0   
1   1995-12-15  262797249.0   104.0   

                                    spoken_languages    status  \
0           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released   

                                     tagline      title  video vote_average  \
0                                        NaN  Toy Story  False          7.7   
1  Roll the dice and unleash the excitement!    Jumanji  False          6.9   

  vote_count  
0     5415.0  
1     2413.0  

[2 rows x 24 columns]

In [97]:
data = data.head(20000) # 상위 2만개의 샘플을 data에 저장
print('overview 열의 결측값의 수:',data['overview'].isnull().sum()) # overview 열에 존재하는 모든 결측값을 전부 카운트하여 출력

overview 열의 결측값의 수: 135


In [98]:
data['overview'] = data['overview'].fillna('') # 결측값을 빈 값으로 대체
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(data['overview'])
print('TF-IDF 행렬의 크기(shape) :',tfidf_matrix.shape)
# 20,000개의 영화(문서 벡터)를 표현하기 위해 총 47,487 개의 단어가 사용됨
# 또는 47,847 차원의 문서 벡터가 20,000개가 존재한다고 표현

TF-IDF 행렬의 크기(shape) : (20000, 47487)


In [99]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix) # 20,000개의 문서 벡터에 대해서 상호 간의 코사인 유사도 확인
print('코사인 유사도 연산 결과 :',cosine_sim.shape) # 20,000행 1: 20,000열 1로 답이 나옴

코사인 유사도 연산 결과 : (20000, 20000)


In [100]:
title_to_index = dict(zip(data['title'], data.index))

# 영화 제목 Father of the Bride Part II의 인덱스를 리턴
idx = title_to_index['Father of the Bride Part II']
print(idx)

4


In [101]:
# 선택한 영화의 제목을 입력하여 코사인 유사도를 통해 가장 overvie 가 유사한 10개의 영화를 찾아내는 함수만들기
def get_recommendations(title, cosine_sim=cosine_sim):
    # 선택한 영화의 타이틀로부터 해당 영화의 인덱스를 받아온다.
    # 해당 영화와 모든 영화와의 유사도를 가져온다.
    # 유사도에 따라 영화들을 정렬한다.
    # 가장 유사한 10개의 영화를 받아온다.
    # 가장 유사한 10개의 영화의 인덱스를 얻는다.
    # 가장 유사한 10개의 영화의 제목을 리턴한다.
  idx = title_to_index[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:11]
  movie_indices = [idx[0] for idx in sim_scores]
  return data['title'].iloc[movie_indices]

get_recommendations('Toy Story')

15348               Toy Story 3
2997                Toy Story 2
10301    The 40 Year Old Virgin
8327                  The Champ
1071      Rebel Without a Cause
11399    For Your Consideration
1932                  Condorman
3057            Man on the Moon
485                      Malice
11606              Factory Girl
Name: title, dtype: object



> 2. 유클리드 거리 (Euclidean distance)
>    : 피타고라스 정리와 같이 두점 사이의 거리를 구하는 것
> 3. 자카드 유사도 (Jaccard similarity)
>    : 합집합에서 교집합의 비율 구하는 것
> 4. 맨하탄 유사도 (Manhattan Similarity)
